# Generated by Django 4.2.2 on 2023-06-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ImageURL',
            field=models.TextField(blank=True, null=True),
        ),
    ]
