# Generated by Django 4.2.2 on 2023-07-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
    ]
